--
-- PostgreSQL database dump
--

\restrict ewB8KlzyM40a4K7XIVehxmEnwHoEcZLIhVPAMWG3Cqx6M6VmJ1eNtazjbkrnbzY

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: todo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.todo (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.todo OWNER TO postgres;

--
-- Name: todo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.todo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.todo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: todo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.todo (id, name) FROM stdin;
1	Read https://en.wikipedia.org/wiki/Pipe_tool
2	Read https://en.wikipedia.org/wiki/Fujikura
3	Read https://en.wikipedia.org/wiki/We_Are_Here_World_Tour
4	Read https://en.wikipedia.org/wiki/Lomovo,_Belgorod_Oblast
5	Read https://en.wikipedia.org/wiki/Villa_La_Palestine
6	Read https://en.wikipedia.org/wiki/Highways_Festival
7	Read https://en.wikipedia.org/wiki/Legend_in_My_Time:_Hank_Wilson_Vol._III
\.


--
-- Name: todo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.todo_id_seq', 7, true);


--
-- Name: todo todo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.todo
    ADD CONSTRAINT todo_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict ewB8KlzyM40a4K7XIVehxmEnwHoEcZLIhVPAMWG3Cqx6M6VmJ1eNtazjbkrnbzY

